# yaml-language-server: $schema=maaspower.schema.json
# NOTE: above relative path to a schema file from 'maaspower schema <filename>'

name: my maas power control webhooks
ip_address: 0.0.0.0
port: 5000
username: test_user
password: test_pass

devices:
  # These require that the server is running on a machine with USB
  # connection to a power control USB hub and the uhubctl utility installed.
  - type: CommandLine
    name: 'raspi(\d+)'
    on: ./poe.sh power on \1
    off: ./poe.sh power off \1
    query: ./poe.sh status \1
    query_on_regex: on
    query_off_regex: off
